[book]
authors = ["Skardis"]
language = "en"
src = "src"
title = "SMOC (Skardis Math On Crack) Documentation"

[output.html]
additional-css = ["theme/custom.css"]
default-theme = "dark"
git-repository-url = "https://github.com/skardis/SMOC"
mathjax-support = true
